actor_lr: 4e-3
critic_lr: 3e-5
cost_critic_lr: 1e-4
temp_lr: 3e-4
lambda_lr: 1e-2
hidden_dims: [256, 256]
discount: 0.99
cost_discount: 0.99
tau: 0.0005
num_qs: 1
num_min_qs: null
critic_dropout_rate: 0
critic_layer_norm: false
target_entropy: -1
init_temperature: 0.1
sampled_backup: true
update_lambda_every: 1
buffer_size: 1000000
use_her: false
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: false
start_steps: 2000
batch_size: 128
utd_ratio: 4
squash_output: True
state_dependent_lambda: False
init_lambda: 100.0
