actor_lr: 0.004
critic_lr: 3e-5
cost_critic_lr: 3e-5
temp_lr: 3e-4
lambda_lr: 3e-5
hidden_dims: [256, 256, 256]
discount: 0.97
cost_discount: 0.99
tau: 0.0005
num_qs: 1
num_min_qs: null
critic_dropout_rate: 0
critic_layer_norm: false
target_entropy: -2
init_temperature: 0.1
sampled_backup: true
buffer_size: 1000000
use_her: true
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: true
start_steps: 2000
batch_size: 128
utd_ratio: 4
squash_output: True
