actor_lr: 1e-3
critic_lr: 3e-4
cost_critic_lr: 5e-4
temp_lr: 3e-4
lambda_lr: 3e-4
hidden_dims: [256, 256]
discount: 0.99
cost_discount: 0.99
tau: 0.00005
num_qs: 2
num_min_qs: null
critic_dropout_rate: 0.01
critic_layer_norm: true
target_entropy: -1
init_temperature: 0.1
sampled_backup: true
update_lambda_every: 1
buffer_size: 1000000
use_her: false
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: false
start_steps: 10000
batch_size: 256
utd_ratio: 10
squash_output: True
state_dependent_lambda: True
init_lambda: 1.0
lambda_regularization: 1.0