max_steps: 4000000
eval_interval: 20000
eval_episodes: 10
tqdm: true
use_wandb: true
wandb_project: constrained-her
load_checkpoint: -1 #20000
load_from_folder: null
train_logging_interval: 50
logging_keys:
  reward: ["cum", "max"]
  cost: ["avg"]
  dense_reward: ["cum"]
  goal_met: ["cum"]