max_steps: 200000
eval_interval: 20000
eval_episodes: 10
tqdm: true
use_wandb: true
wandb_project: constrained-her
load_checkpoint: 200000
load_from_folder: /home/jakob/Promotion/code/n-dim-reach-env/outputs/2022-11-24/09-01-04/
train_logging_interval: 50
logging_keys:
  reward: ["cum", "max"]
  cost: ["avg"]
  dense_reward: ["cum"]
  goal_met: ["cum"]