actor_lr: 0.0003
critic_lr: 0.0001
temp_lr: 3e-4
hidden_dims: [64, 64]
discount: 0.99
tau: 0.0005
num_qs: 3
num_min_qs: null
critic_dropout_rate: 0.002
critic_layer_norm: false
target_entropy: -1
init_temperature: 0.1
sampled_backup: true
buffer_size: 1000000
use_her: true
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: false
boost_single_demo: false
pre_play_steps: 30000
pre_play_rate: 0.5
start_steps: 2000
batch_size: 128
utd_ratio: 5
squash_output: True
