actor_lr: 1e-3
critic_lr: 1e-3
feature_extractor_lr: 1e-3
feature_extractor_dims: null
network_dims: [256, 256]
discount: 0.98
tau: 5e-3
action_noise_std: 0.1
action_noise_clip: 0.2
buffer_size: 1000000
use_her: true
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: false
start_steps: 2000
batch_size: 128
utd_ratio: 4
squash_output: True