actor_lr: 0.004
critic_lr: 3e-5
feature_extractor_lr: 3e-4
temp_lr: 3e-4
feature_extractor_dims: [256, 256]
network_dims: [64, 64]
discount: 0.99
tau: 0.0005
target_entropy: -1
init_temperature: 0.1
sampled_backup: true
buffer_size: 1000000
use_her: true
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: false
start_steps: 2000
batch_size: 128
utd_ratio: 5
squash_output: True