actor_lr: 1e-3
critic_lr: 1e-3
feature_extractor_lr: 1e-3
temp_lr: 1e-3
feature_extractor_dims: null
network_dims: [256, 256]
discount: 0.98
tau: 5e-3
target_entropy: -1
init_temperature: 0.1
sampled_backup: true
buffer_size: 1000000
use_her: true
n_her_samples: 4
goal_selection_strategy: future
handle_timeout_termination: false
start_steps: 10000
batch_size: 128
utd_ratio: 4
squash_output: True